### ISSUE TITLE
Not used icons should not appear in output bundle

### ISSUE THREAD

**Issue by alessiosantangelo** [primait/pyxis#81]
At the time of writing, our icons are fully generated by a script inside `pyxis/packages/pyxis-icons`.
This script is responsible of looking for all of our physical svg-icons and transforming them into an Elm type representation. 

This is done for all the icons without considering if they're used by the application or not. This kind of solution enlarges the output bundle.

We should try to reduce the bundle size by using dead-code elimination techniques. @kioan000 had some tries with a concept for a Webpack build, we should give a try to his solution in order to lighten our bundle.

**Comment by ascandone** [comment]
A previous implementation generated something like:

```elm
-- Implementation

type Icon = Icon (Html Never)

arrowIcon : Icon
arrowIcon = Icon ( Svg.svg [] [] ... inline svg )

render : Config -> Icon -> Html msg
render config (Icon icon) =
	Html.div [ ... insert here the attributes using config]
		[ Html.map never icon ]


-- Usage

Icon.arrowIcon
|> Icon.withOnClick ClickedIcon
|> Icon.render
```

This is the simpliest way to implement tree-shaking without complex bundler features or without depending on a specific bundling library (eg. there are projects using parcel right now)

Is there a way this was discarded? If the problem is to separate `Icon` and `IconSet`, this can be done easily
